version: 2
jobs:
  build:
    docker:
      - image: a6kme/node-aws-cli:v1
    branches:
      only:
        - master
    environment:
      - AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      - CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID
    steps:
      - run: npm install
      - run: npm run build
      - run: npm run export
      - run: s3 sync ./out s3://a6kme-site-artifacts/
      - run: cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"