version: 2
jobs:
  build:
    docker:
      - image: a6kme/node-aws-cli:v3
    branches:
      only: master
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run export
      - run: aws s3 sync ./out s3://a6kme-site-artifacts/
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"